export class ProductsData {
  data: any = [
    {title: 'Axial fan', sub_title: 'AKSTS160-03', type: 1, img:'axial_fan.png', img_mini:'axial_fan-mini.png', text:'Axial fans are designed that Ø1000, Ø1250, Ø1400, Ø1600 diameter sizes to circulation of dry and humidity air in the system.'},
    {title: 'Radial fan (Down Direction)', sub_title: 'RDY50A-AŞAĞI BAKAN', img:'radial-fan-down-direction.png',img_mini:'radial-fan-down-direction-mini.png', text:'To enable the high pressures airflow with a power specification matching to operation for every requirement. High efficiency with special impeller design. Available with intake on both sides.'},
    {title: 'Radial FAN (Up Direction)', sub_title: 'RDY50Y-YUKARI BAKAN', img:'radial-fan-up-direction.png',img_mini:'radial-fan-up-direction-mini.png', text:'To enable the high pressures airflow with a power specification matching to operation for every requirement. High efficiency with special impeller design. Available with intake on both sides.'},
    {title: 'High capacity material transport fan', sub_title: 'PNF-01', img:'1_high-capacity-material-transport-fan.png',img_mini:'1_high-capacity-material-transport-fan-mini.png', text:'To enable the high pressure airflow at the Pneumafil line which is available with intake on one side. High efficiency with special impeller design.',detail1: 'General Usage: Pneumafile transportation', detail2: 'Max. Capacity : 3000 Pa & 18000 m3/h'},
    {title: 'PRE-FILTER (Top Suction)', sub_title: 'OF200Y-04', img:'prefilter-top-suction.png',img_mini:'prefilter-top-suction-mini.png', text:'Prefilter is used for coarse waste material filtration with the different sizes like Ø1300, Ø2000, Ø2500, Ø3000(Weaving Unit), Ø3500(Weaving Unit). No fiber contamination with the optimum velocity selection.'},
    {title: 'ROTARY FILTER', sub_title: '', img:'1_rotary-filter.png',img_mini:'1_rotary-filter-mini.png', text:'Rotary filter is a system element that filters dust and fibres in the air. that is collected from the hall and machine exhausts. ',detail1: 'Diameters: 02000 mm, 02500 mm, 03000 mm, 03500 mm, 170cm, 340cm, 510cm, 680cm in Ieng Electrostatic Powder Paint Co ted to prevent corrosion. 8mm, %100 Acrylic, 360-460 gr/m2Easy to CLEAN Filter Media Cover. Especially designed Double Section Nozzle with SUPERB Performance.', detail2: ''},
    {title: 'PERPENDICULAR FILTER', sub_title: 'DKF115', img:'perpendicular-filter.png',img_mini:'perpendicular-filter-mini.png', text:'Pre-filtering of fiber material with the radial fan suction at the specific and low capacity applications.', detail1: 'Diameters: 1150mm, 1250mm, 1600mm', detail2: 'Max capacity: 25000 m3/h'},
    {title: 'FIBRE COMPACTOR (Big)', sub_title: 'KMP-01', type: 1, img:'fibre-compactor-big.png', img_mini:'fibre-compactor-big-mini.png', text:'To separate and clean dust and waste. With 80-150kg/h waste capacity. Brush and brushless screw design with respect to waste material. With Temsan Pressure Switch Control for high efficieny and energy saving. Maximum 250kg/h waste capacity.'},
    {title: 'WASTE SILO', sub_title: 'TTP-03', type: 1, img:'waste-collection-waste-sylo.png', img_mini:'waste-collection-waste-sylo-mini.png', text:'3 fibre compactor can be connected to each silo (15m3 waste capacity). Waste materials are automatically collected at the silos with the less labor cost. Spray nozzle fire protection. Level control sensor Inverter control feeding.'},
    {title: 'FIBRE SEPARATOR (CONDENSER)', sub_title: 'KNDN-01', type: 1, img:'fibre-separator-condenser.png', img_mini:'fibre-separator-condenser-mini.png', text:'To transport cotton and synthetic fibers in the form\n' +
        'of tuft with high efficiency.', detail1: 'Air Volume: 4500-7500 m3/h', detail2: 'Max. Capacity: 1200 kg/h'},
    {title: 'Axial fan', sub_title: 'AKSTS160-03', type: 1, img:'axial_fan.png', img_mini:'axial_fan-mini.png', text:'Axial fans are designed that Ø1000, Ø1250, Ø1400, Ø1600 diameter sizes to circulation of dry and humidity air in the system.'},
    {title: 'Axial fan', sub_title: 'AKSTS160-03', type: 1, img:'axial_fan.png', img_mini:'axial_fan-mini.png', text:'Axial fans are designed that Ø1000, Ø1250, Ø1400, Ø1600 diameter sizes to circulation of dry and humidity air in the system.'},
    {title: 'Axial fan', sub_title: 'AKSTS160-03', type: 1, img:'axial_fan.png', img_mini:'axial_fan-mini.png', text:'Axial fans are designed that Ø1000, Ø1250, Ø1400, Ø1600 diameter sizes to circulation of dry and humidity air in the system.'},
    {title: 'Axial fan', sub_title: 'AKSTS160-03', type: 1, img:'axial_fan.png', img_mini:'axial_fan-mini.png', text:'Axial fans are designed that Ø1000, Ø1250, Ø1400, Ø1600 diameter sizes to circulation of dry and humidity air in the system.'},
    {title: 'Axial fan', sub_title: 'AKSTS160-03', type: 1, img:'axial_fan.png', img_mini:'axial_fan-mini.png', text:'Axial fans are designed that Ø1000, Ø1250, Ø1400, Ø1600 diameter sizes to circulation of dry and humidity air in the system.'},
  ];

  productList: any = [
    {name:'Axial Fan', value:'1'},
    {name:'Radial Fan(Down Direction)', value:'2'},
    {name:'Radial Fan(Up Direction)', value:'3'},
    {name:'High Capacity Material Transport Fan', value:'4'},
    {name:'Pre-Filter (Top Suction)', value:'5'},
    {name:'Rotary Filter', value:'6'},
    {name:'Perpendicular Filter', value:'7'},
    {name:'Fibre Compactor (Big)', value:'8'},
    {name:'Waste Silo', value:'9'},
    {name:'Fibre Separator (Condenser)', value:'10'},
    {name:'Waste Separator', value:'11'},
    {name:'Automatic Dust Collection Unit', value:'12'},
    {name:'Dust Brick Press', value:'13'},
    {name:'Conveyor Band System With The Fibre Compactor', value:'14'},
    {name:'Hydraulic Bale Press', value:'15'},
    {name:'Housing Type Package Filter', value:'16'},
    {name:'Housing Type Package A/C', value:'17'},
    {name:'Air Washer (Prefabricated)', value:'18'},
    {name:'Rotary Water Filter', value:'19'},
    {name:'Material Transport Fan', value:'20'},
    {name:'Dust Fan', value:'21'},
    {name:'Btf Fan', value:'22'},
    {name:'Radial Fan(Comber Fan)', value:'23'},
    {name:'Dust Collector', value:'24'},
    {name:'Dampers', value:'25'},
    {name:'Doors', value:'26'},
    {name:'Ground Slots', value:'27'},
    {name:'Diffuser For Weaving Units', value:'28'},
    {name:'DUCT TYPE DIFFUSER', value:'29'},
    {name:'AIR DISTRIBUTING PLATES', value:'30'},
    {name:'SERPENTINES', value:'31'},
    {name:'SLIDING DAMPERS', value:'32'},
    {name:'ROVING OPENER', value:'33'},
    {name:'BATCHING UNIT (Inclined)', value:'34'},
    {name:'BATCHING UNIT (Inclined)', value:'35'},
    {name:'ELECTRONICAL INSTRUMENTS', value:'36'},
    {name:'ELECTRIC PANEL', value:'37'},
    {name:'AUTOMATION PANEL', value:'38'},
  ]
}
